[project]
name = "pp-aut-2026"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "argon2-cffi>=25.1.0",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[all]>=0.141.1",
    "greenlet>=3.5.6",
    "pyjwt>=2.15.1",
    "python-jwt>=4.1.0",
    "redis>=8.1.0",
    "ruff>=0.16.9",
    "sqlalchemy>=2.1.1",
]
